### ISSUE TITLE
onfigure: error: Unable to find a usable isl. 

### ISSUE THREAD

**Issue by great-thoughts** [sol-prog/gcc-osx-binary#1]
When I compile gcc I get the following error: configure: error: Unable to find a usable isl.  See config.log for details.

**Comment by sol-prog** [comment]
The error tells you that you didn't correctly compiled ISL. Check the blog post https://solarianprogrammer.com/2017/05/21/compiling-gcc-macos/ for the entire procedure.

**Comment by RoyiAvital** [comment]
Hi,

It seems OpenMP library is also missing.
Also, in macOS, should I add the `include` and `lib` folders of GCC to the path as well?

**Comment by sol-prog** [comment]
@RoyiAvital Actually it is not missing. What version of macOS are you using ? Have you installed the command line tools first ?

**Comment by RoyiAvital** [comment]
I will copy the comment I left on your blog:

> Hello,
>
> I'm trying to use your Binary as a Portable Independent Compiler.
Something similar to the way I use MinGW64 + GCC in Windows (See https://github.com/StephanT....
>
> I extracted your binary file into /Users/Shared/GCC/.
> Then I open a terminal which I add the path to the `bin` sub folder into the path (I verify this using `gcc-8.1 --help` which indeed works).
> 
> Then I try to compile simple test case (Gaussian Blur) with the following:
> 
> g++-8.1 -Ofast -fopenmp GaussianBlurMain.cpp GaussianBlurUnitTest.cpp GaussianBlur.cpp -o GaussianBlur
> 
> I get the following error:
> 
> dyld: Library not loaded: /usr/local/gcc-8.1/lib/libisl.15.dylib
> Referenced from: /Users/Shared/GCC/bin/../libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/cc1plus
> Reason: image not found
> 
> The code does work with different compiler.
> 
> Any idea?
> Is there a way to replicate the GCC capabilities above?
> Is there a way to make the SymLinks to be relative to the location of gcc-8.1 / g++-8.1?

It seems I have issues with SymLinks or something.

**Comment by sol-prog** [comment]
Sorry, but it seems you are not actually reading the instructions from the binary web page. You are putting the extracted binary in the wrong place.

Read the text from https://bitbucket.org/sol_prog/macos-gcc-binary where the binary is currently located.

**Comment by RoyiAvital** [comment]
@sol-prog ,
I understood there is an issue with the SymLinks / Relative Paths.
I'm asking if there is something I can do that the binary is working in any path it is installed (Like GCC works in Windows).

Can it be done?

**Comment by RoyiAvital** [comment]
@sol-prog ,

I get this error:

```
static float const a = 12102203.2f; // (1 << 23) / ln(2)
     ^~~~~~
libbacktrace could not find executable to open
```

Any idea?
